name: upharm_common
description: "upharm_common"
version: 0.0.11

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_size_text: ^3.0.0
  collection: ^1.18.0
  data_table_2: ^2.5.12
  dropdown_button2: ^2.3.9
  flutter_animate: ^4.1.1+1
  font_awesome_flutter: ^10.6.0
  from_css_color: ^2.0.0
  go_router: ^13.2.1
  google_fonts: ^6.1.0
  intl: ^0.18.1
  json_path: ^0.7.1
  mask_text_input_formatter: ^2.4.0
  page_transition: ^2.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  timeago: ^3.2.2
  url_launcher: ^6.1.10
  uuid: ^3.0.7
  rxdart: ^0.27.7
  auto_exporter: ^3.0.2
  json_annotation: ^4.8.1
  signalr_netcore: ^0.1.7+2-nullsafety.3

dev_dependencies:
  flutter_lints: ^3.0.1
  dependency_validator: ^3.2.3

  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true